const ShopActionTypes ={
          FETCH_SINGLE_PRODUCT : 'FETCH_SINGLE_PRODUCT',
          FETCH_SINGLE_PRODUCT_SUCCESS:'FETCH_SINGLE_PRODUCT_SUCCESS',
          FETCH_SINGLE_PRODUCT_FAILURE:'FETCH_SINGLE_PRODUCT_FAILURE',
          FETCH_DATA_START:'FETCH_DATA_START',
          FETCH_DATA_SUCCESS:'FETCH_DATA_SUCCESS',
          FETCH_DATA_FAILURE:'FETCH_DATA_FAILURE',
          FETCH_SEARCH:"FETCH_SEARCH",
          FETCH_SEARCH_SUCCESS:'FETCH_SEARCH_SUCCESS',
          FETCH_SEARCH_FAILURE:'FETCH_SEARCH_FAILURE',
          PAGINATION_ITEM:'PAGINATION_ITEM',
          FETCH_RELATE_PRODUCT:'FETCH_RELATE_PRODUCT',
          FETCH_RELATE_PRODUCT_SUCCESS:'FETCH_RELATE_PRODUCT_SUCCESS',
          FETCH_RELATE_PRODUCT_FAILURE:'FETCH_RELATE_PRODUCT_FAILURE',
          RESET_SINGLE_PRODUCT:'RESET_SINGLE_PRODUCT'
}
export default ShopActionTypes